"""Machine-readable API contract derived from the actually served route table.

The contract is generated by walking the application's routes, so it cannot
claim an endpoint that is not served. A drift test compares this output against
``DASHBOARD_RESOURCES`` and the mandatory route list.
"""
from __future__ import annotations

import json
from pathlib import Path

from starlette.routing import Route

from agent.dashboard_contracts import DASHBOARD_RESOURCES

CONTRACT_VERSION = "1.0.0"

# Routes the public API release must serve. Kept explicit so an accidental
# deletion fails a test rather than silently shrinking the surface.
MANDATORY_ROUTES = {
    ("GET", "/healthz"),
    ("GET", "/readyz"),
    ("POST", "/github/webhook"),
    ("POST", "/api/deployments/events"),
    ("POST", "/api/monitoring/baselines"),
    ("POST", "/api/monitoring/observations"),
    ("GET", "/api/monitoring/observations"),
    ("POST", "/api/anomalies"),
    ("GET", "/api/anomalies"),
    ("POST", "/api/incidents"),
    ("GET", "/api/incidents"),
    ("POST", "/api/reviews"),
    ("GET", "/api/reviews"),
    ("GET", "/api/reviews/{review_id}"),
    ("GET", "/api/deployments"),
    ("GET", "/api/deployments/{deployment_id}"),
    ("GET", "/api/monitoring"),
    ("GET", "/api/incidents/{incident_id}"),
    ("GET", "/api/incidents/{incident_id}/rca"),
    ("GET", "/api/models/{model}/lineage"),
    ("GET", "/api/kpis/{kpi}/impact"),
    ("GET", "/api/repositories/{repository}/settings"),
    ("GET", "/api/evidence-coverage"),
    ("GET", "/api/delivery-status"),
    # metadata evidence plane
    ("GET", "/api/collection-requests"),
    ("GET", "/api/collection-requests/{request_id}"),
    ("POST", "/api/collection-requests/{request_id}/acknowledge"),
    ("POST", "/api/collection-requests/{request_id}/failure"),
    ("POST", "/api/manifest-evidence"),
    ("POST", "/api/metadata-snapshots"),
    ("GET", "/api/metadata-snapshots/{snapshot_id}"),
    ("GET", "/api/reviews/{review_id}/evidence-coverage"),
    ("POST", "/api/collectors"),
    # Review detail surface. These expose evidence the store already held but
    # nothing could read: findings, attempt history, what was requested from
    # the collector, which snapshots answered it, and where it was published.
    ("POST", "/api/reviews/{review_id}/rerun"),
    ("POST", "/api/reviews/{review_id}/request-changes"),
    ("GET", "/api/reviews/{review_id}/change-requests"),
    ("POST", "/api/reviews/{review_id}/exceptions"),
    ("GET", "/api/reviews/{review_id}/exceptions"),
    ("POST", "/api/reviews/{review_id}/exceptions/{exception_id}/revoke"),
    ("GET", "/api/reviews/{review_id}/findings"),
    ("GET", "/api/reviews/{review_id}/attempts"),
    # The downloadable evidence bundle for ONE attempt. Declared separately
    # from the attempt list because it is a different disclosure decision: the
    # list carries the comparison, this carries the full bounded observations
    # behind it.
    ("GET", "/api/reviews/{review_id}/attempts/{attempt}/metadata-evidence.json"),
    # The human-readable counterpart: the canonical impact report for ONE
    # attempt, as Markdown. Same evidence, different artifact.
    ("GET", "/api/reviews/{review_id}/attempts/{attempt}/impact-report.md"),
    ("GET", "/api/reviews/{review_id}/collection-requests"),
    ("GET", "/api/reviews/{review_id}/snapshots"),
    ("GET", "/api/reviews/{review_id}/publications"),
    # First-run onboarding. Authenticated by a server-verified Clerk session
    # token rather than a service token — see ONBOARDING_AUTHENTICATED below.
    ("GET", "/api/onboarding/state"),
    ("PUT", "/api/tenants"),
    ("POST", "/api/onboarding/github/identity"),
    ("POST", "/api/onboarding/github/install"),
}

AUTHENTICATION = {
    "/healthz": "none",
    "/readyz": "none",
    "/github/webhook": "github-webhook-signature",
    # A Clerk session token, verified server-side against Clerk's JWKS. Named
    # distinctly from "service-token" because it is a different principal with
    # a different authorization model, and the contract should say so rather
    # than blur two credentials into one label.
    "/api/onboarding/state": "clerk-session",
    "/api/tenants": "clerk-session",
    "/api/onboarding/github/identity": "clerk-session",
    "/api/onboarding/github/install": "clerk-session",
    # Browser redirects arriving from github.com. They cannot carry a header,
    # and a cookie would be sent cross-site, so the credential is the
    # single-use installation state itself. Named distinctly because it is a
    # weaker claim than a session: it says which flow this is, not what was
    # installed — every other value on the request is verified against GitHub.
    "/auth/github/link/callback": "installation-state",
    "/github/setup": "installation-state",
}

#: Every authentication mode that counts as authenticated. An /api route whose
#: mode is absent from this set is unauthenticated, which is the thing the
#: contract test exists to prevent.
AUTHENTICATED_MODES = frozenset({"service-token", "clerk-session"})


def served_routes(app) -> list[dict]:
    """Every (method, path) pair the application actually serves."""
    entries = []
    for route in app.routes:
        if not isinstance(route, Route):
            continue
        for method in sorted(route.methods or set()):
            if method in {"HEAD", "OPTIONS"}:
                continue
            entries.append({
                "method": method,
                "path": route.path,
                "authentication": AUTHENTICATION.get(route.path, "service-token"),
            })
    entries.sort(key=lambda e: (e["path"], e["method"]))
    return entries


def build_contract(app) -> dict:
    entries = served_routes(app)
    return {
        "contract_version": CONTRACT_VERSION,
        "routes": entries,
        "dashboard_resources": dict(sorted(DASHBOARD_RESOURCES.items())),
        "mandatory_routes": sorted(f"{m} {p}" for m, p in MANDATORY_ROUTES),
    }


def contract_drift(app) -> dict:
    """Differences between the declared contract and the served route table."""
    served = {(e["method"], e["path"]) for e in served_routes(app)}
    served_paths = {path for _, path in served}

    unserved_dashboard = sorted(
        f"{name} -> {path}"
        for name, path in DASHBOARD_RESOURCES.items()
        if path not in served_paths
    )
    missing_mandatory = sorted(f"{m} {p}" for m, p in MANDATORY_ROUTES - served)
    undeclared_api = sorted(
        f"{m} {p}" for m, p in served
        if p.startswith("/api/") and (m, p) not in MANDATORY_ROUTES
    )
    return {
        "unserved_dashboard_resources": unserved_dashboard,
        "missing_mandatory_routes": missing_mandatory,
        "undeclared_api_routes": undeclared_api,
        "drift_free": not (unserved_dashboard or missing_mandatory or undeclared_api),
    }


def write_contract(app, path) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    # An explicit LF newline matters: the contract is a checked-in artifact
    # compared byte for byte by the drift test and by `git diff --check`, so
    # it must not pick up platform line endings from whoever regenerated it.
    target.write_text(
        json.dumps(build_contract(app), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return target
