"""Machine-readable API contract derived from the actually served route table.

The contract is generated by walking the application's routes, so it cannot
claim an endpoint that is not served. A drift test compares this output against
``DASHBOARD_RESOURCES`` and the mandatory route list.
"""
from __future__ import annotations

import json
from pathlib import Path

from starlette.routing import Route

from agent.dashboard_contracts import DASHBOARD_RESOURCES

CONTRACT_VERSION = "1.0.0"

# Routes the public API release must serve. Kept explicit so an accidental
# deletion fails a test rather than silently shrinking the surface.
MANDATORY_ROUTES = {
    ("GET", "/healthz"),
    ("GET", "/readyz"),
    ("POST", "/github/webhook"),
    ("POST", "/api/deployments/events"),
    ("POST", "/api/monitoring/baselines"),
    ("POST", "/api/monitoring/observations"),
    ("GET", "/api/monitoring/observations"),
    ("POST", "/api/anomalies"),
    ("GET", "/api/anomalies"),
    ("POST", "/api/incidents"),
    ("GET", "/api/incidents"),
    ("POST", "/api/reviews"),
    ("GET", "/api/reviews"),
    ("GET", "/api/reviews/{review_id}"),
    ("GET", "/api/deployments"),
    ("GET", "/api/deployments/{deployment_id}"),
    ("GET", "/api/monitoring"),
    ("GET", "/api/incidents/{incident_id}"),
    ("GET", "/api/incidents/{incident_id}/rca"),
    ("GET", "/api/models/{model}/lineage"),
    ("GET", "/api/kpis/{kpi}/impact"),
    ("GET", "/api/repositories/{repository}/settings"),
    ("GET", "/api/evidence-coverage"),
    ("GET", "/api/delivery-status"),
}

AUTHENTICATION = {
    "/healthz": "none",
    "/readyz": "none",
    "/github/webhook": "github-webhook-signature",
}


def served_routes(app) -> list[dict]:
    """Every (method, path) pair the application actually serves."""
    entries = []
    for route in app.routes:
        if not isinstance(route, Route):
            continue
        for method in sorted(route.methods or set()):
            if method in {"HEAD", "OPTIONS"}:
                continue
            entries.append({
                "method": method,
                "path": route.path,
                "authentication": AUTHENTICATION.get(route.path, "service-token"),
            })
    entries.sort(key=lambda e: (e["path"], e["method"]))
    return entries


def build_contract(app) -> dict:
    entries = served_routes(app)
    return {
        "contract_version": CONTRACT_VERSION,
        "routes": entries,
        "dashboard_resources": dict(sorted(DASHBOARD_RESOURCES.items())),
        "mandatory_routes": sorted(f"{m} {p}" for m, p in MANDATORY_ROUTES),
    }


def contract_drift(app) -> dict:
    """Differences between the declared contract and the served route table."""
    served = {(e["method"], e["path"]) for e in served_routes(app)}
    served_paths = {path for _, path in served}

    unserved_dashboard = sorted(
        f"{name} -> {path}"
        for name, path in DASHBOARD_RESOURCES.items()
        if path not in served_paths
    )
    missing_mandatory = sorted(f"{m} {p}" for m, p in MANDATORY_ROUTES - served)
    undeclared_api = sorted(
        f"{m} {p}" for m, p in served
        if p.startswith("/api/") and (m, p) not in MANDATORY_ROUTES
    )
    return {
        "unserved_dashboard_resources": unserved_dashboard,
        "missing_mandatory_routes": missing_mandatory,
        "undeclared_api_routes": undeclared_api,
        "drift_free": not (unserved_dashboard or missing_mandatory or undeclared_api),
    }


def write_contract(app, path) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(build_contract(app), indent=2, sort_keys=True), encoding="utf-8"
    )
    return target
