CREATE TABLE IF NOT EXISTS tenants (organization_id TEXT NOT NULL, repository_id TEXT NOT NULL, environment TEXT NOT NULL, connected INTEGER NOT NULL DEFAULT 1, PRIMARY KEY (organization_id, repository_id, environment));
CREATE TABLE IF NOT EXISTS evidence (evidence_id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, repository_id TEXT NOT NULL, environment TEXT NOT NULL, payload TEXT NOT NULL, content_hash TEXT NOT NULL, UNIQUE (organization_id, repository_id, environment, content_hash));
CREATE TABLE IF NOT EXISTS deployments (deployment_id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, repository_id TEXT NOT NULL, environment TEXT NOT NULL, payload TEXT NOT NULL, status TEXT NOT NULL, UNIQUE (organization_id, repository_id, environment, deployment_id));
CREATE TABLE IF NOT EXISTS deployment_transitions (transition_id INTEGER PRIMARY KEY AUTOINCREMENT, deployment_id TEXT NOT NULL, organization_id TEXT NOT NULL, repository_id TEXT NOT NULL, environment TEXT NOT NULL, from_status TEXT, to_status TEXT NOT NULL, sequence INTEGER NOT NULL, created_at TEXT NOT NULL, UNIQUE (deployment_id, sequence));
CREATE TABLE IF NOT EXISTS outbox_events (event_id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, repository_id TEXT NOT NULL, environment TEXT NOT NULL, deployment_id TEXT NOT NULL, event_type TEXT NOT NULL, payload TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'PENDING', lease_owner TEXT, attempts INTEGER NOT NULL DEFAULT 0, UNIQUE (organization_id, repository_id, environment, deployment_id, event_type));
CREATE TABLE IF NOT EXISTS retention_tombstones (organization_id TEXT PRIMARY KEY, deleted_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS configuration_versions (organization_id TEXT NOT NULL, repository_id TEXT NOT NULL, environment TEXT NOT NULL, policy_version TEXT, detector_version TEXT, threshold_version TEXT, created_at TEXT NOT NULL, PRIMARY KEY (organization_id, repository_id, environment));
CREATE TABLE IF NOT EXISTS event_receipts (event_id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, repository_id TEXT NOT NULL, environment TEXT NOT NULL, status TEXT NOT NULL, response TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS lineage_records (lineage_id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, repository_id TEXT NOT NULL, environment TEXT NOT NULL, model TEXT NOT NULL, payload TEXT NOT NULL, UNIQUE (organization_id, repository_id, environment, lineage_id));
